# Generated by Django 4.0.3 on 2022-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
